"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Equipo_1 = require("./Equipo");
var Bomba_1 = require("./Bomba");
var KitMangueras_1 = require("./KitMangueras");
var Motor_1 = require("./Motor");
var MotorElectrico_1 = require("./MotorElectrico");
var MotorCombustible_1 = require("./MotorCombustible");
var bomba1 = new Bomba_1.Bomba('B1', 4, 5, 'Jgh');
bomba1.getleerBomba;
bomba1.modificarBomba('B1_2', 4.1, 5.1, 'Kartan');
bomba1.getleerBomba;
var manguera1 = new KitMangueras_1.KitMangueras('id Rosca', 5, 1 / 8, KitMangueras_1.Roscas.material1);
manguera1.getleerKitMangueras;
manguera1.modificarKitMangueras('id Rosca', 5, 1 / 8, KitMangueras_1.Roscas.material3);
manguera1.getleerKitMangueras;
var MCombustion = new MotorCombustible_1.MotorCombustible('id MC', 1000, Motor_1.Eficiencia.B, 'Acme', '3CV', MotorCombustible_1.Combustible.Diesel);
MCombustion.motorCombustible;
MCombustion.modificarMotorCombustible('id MC', 1000, Motor_1.Eficiencia.B, 'Acme', '3CV', MotorCombustible_1.Combustible.Gasolina);
MCombustion.motorCombustible;
var MEleictrico1 = new MotorElectrico_1.MotorElectrico('id ME', 1000, Motor_1.Eficiencia.A, 'Acme', 'Amp', 15, true);
MEleictrico1.leerMotorElectrico;
MEleictrico1.modificarMotorElectrico('id ME', 1000, Motor_1.Eficiencia.A, 'Acme', 'Amp', 15, false);
MEleictrico1.leerMotorElectrico;
var equipo1 = new Equipo_1.Equipo('id motor E', 'desc motor', new Date(), new Date(), bomba1, manguera1, MEleictrico1);
equipo1.getleerEquipo;
var equipo2 = new Equipo_1.Equipo('id motor', 'desc motor', new Date(), new Date(), bomba1, manguera1, MCombustion);
equipo2.getleerEquipo;
var equipos = [];
equipos.push(equipo1);
equipos.push(equipo2);
console.log(equipos);
equipo1.eliminaEquipo(equipos);
console.log(equipos);
